Max/error formatter
reset-button/ariadne_django pull request #37
Opened 2021-06-06 03:13 UTC by maxmorlocke

Provide a default, simple error formatter designed to provide sane values out of the box

2021-06-07 17:24 UTC, Smona approved these changes
lgtm! just one suggestion on error messaging

2021-06-07 17:24 UTC, Smona commented on ariadne_django/formatters/errors/simple.py
> +        "details": {"non_field_errors": (["This request is understood, but is not able to be processed."])},
It might be better to make some mention of authorization here. This error message doesn't make clear that permission was denied.

2021-06-09 16:54 UTC, drewsynan requested changes
generally looks great to me! can you address/comment on the few points I raised?

2021-06-09 16:54 UTC, drewsynan commented on ariadne_django/formatters/errors/simple.py
> +    Django error messaging around.
```suggestion
    Django error messaging around as possible.
```

2021-06-09 16:54 UTC, drewsynan commented on ariadne_django/formatters/errors/simple.py
> +    formatted = error.formatted
thinking it's good hygiene to not mutate the original error object. how do you feel about
```
formatted = copy(error.formatted)
```
?

2021-06-09 16:54 UTC, drewsynan commented on ariadne_django/formatters/errors/utils/extract_original_error.py
> +    if getattr(error, "original_error", None):
```suggestion
    if getattr(error, "original_error", None) is not None:
```

2021-06-09 16:54 UTC, drewsynan commented on ariadne_django/formatters/errors/utils/get_postgres_error_details.py
> +    error_code = getattr(getattr(error, "__cause__", None), "pgcode", None)
```suggestion
    cause = getattr(error, "__cause__", None)
    error_code = getattr(cause, "pgcode", None)
```

2021-06-09 16:54 UTC, drewsynan commented on ariadne_django/formatters/errors/utils/get_postgres_error_details.py
> +    elif error_code.startswith("22") or (error_code.startswith("23") and error_code not in ["23505"]):
can you convert these magic strings to named vars? I know this fn is small in scope, but `PG_INTEGRITY_CONSTRAINT_VIOLATION` is a lot clearer to me than `"23"`

2022-07-19 03:43 UTC, merged